[build]
builder = "docker"

[deploy]
strategy = "dockerfile"

[phases.setup]
image = "mcr.microsoft.com/dotnet/sdk:8.0"

[phases.build]
cmds = [
  'dotnet restore',
  'dotnet publish -c Release -o out'
]

[start]
cmd = "dotnet out/Dualite.dll"
