apiVersion: apps/v1
kind: Deployment
metadata:
  name: dualite-api-gateway
  namespace: dualite
  labels:
    app: dualite-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dualite-api-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dualite-api-gateway
    spec:
      containers:
      - name: api-gateway
        image: dualite/dualite-api:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: dualite-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: dualite-secrets
              key: DB_CONNECTION_STRING
        - name: Redis__ConnectionString
          valueFrom:
            secretKeyRef:
              name: dualite-secrets
              key: REDIS_CONNECTION_STRING
        - name: EmailNlpService__BaseUrl
          valueFrom:
            configMapKeyRef:
              name: dualite-config
              key: EMAIL_NLP_SERVICE_URL
        - name: InvoiceParserService__BaseUrl
          valueFrom:
            configMapKeyRef:
              name: dualite-config
              key: INVOICE_PARSER_SERVICE_URL
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: dualite-api-gateway
  namespace: dualite
spec:
  selector:
    app: dualite-api-gateway
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  type: ClusterIP
