apiVersion: apps/v1
kind: Deployment
meta:
  name: dualite-email-nlp
  namespace: dualite
  labels:
    app: dualite-email-nlp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dualite-email-nlp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    meta:
      labels:
        app: dualite-email-nlp
    spec:
      containers:
      - name: email-nlp
        image: dualite/dualite-email-nlp:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dualite-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: dualite-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: dualite-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dualite-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dualite-secrets
              key: DB_PASSWORD
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: dualite-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: dualite-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: dualite-secrets
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dualite-secrets
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_QUEUE
          value: "email_processing"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: dualite-secrets
              key: REDIS_URL
        - name: REDIS_DEFAULT_TTL
          value: "3600"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
meta:
  name: dualite-email-nlp
  namespace: dualite
spec:
  selector:
    app: dualite-email-nlp
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
