apiVersion: v1
kind: Secret
metadata:
  name: dualite-secrets
  namespace: dualite
type: Opaque
stringData:
  # These values should be replaced with actual secrets in a secure manner
  # Do NOT commit actual secrets to version control
  # Use a secret management solution like Kubernetes Secrets, HashiCorp Vault, or AWS Secrets Manager in production
  DB_CONNECTION_STRING: "Server=postgres-service;Port=5432;Database=dualite;User Id=dualite_user;Password=REPLACE_ME;"
  DB_USER: "dualite_user"
  DB_PASSWORD: "REPLACE_ME"
  REDIS_CONNECTION_STRING: "redis-service:6379,password=REPLACE_ME"
  REDIS_URL: "redis://default:REPLACE_ME@redis-service:6379/0"
  RABBITMQ_USERNAME: "dualite_user"
  RABBITMQ_PASSWORD: "REPLACE_ME"
